use crate::types::QuestionTypeKind;
use crate::types::QuestionTypeKind::*;

pub struct DifficultyProfile {
    pub question_count: usize,
    pub allowed_types: &'static [QuestionTypeKind],
}

pub static PROFILES: [DifficultyProfile; 5] = [
    DifficultyProfile {
        question_count: 4,
        allowed_types: &[CountAnswer, AnswerOf, AnswerIsSelf, FirstWith, LastWith],
    },
    DifficultyProfile {
        question_count: 5,
        allowed_types: &[
            CountAnswer,
            AnswerOf,
            AnswerIsSelf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            NextSame,
            PrevSame,
        ],
    },
    DifficultyProfile {
        question_count: 8,
        allowed_types: &[
            CountAnswer,
            AnswerOf,
            AnswerIsSelf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            NextSame,
            PrevSame,
            LeastCommon,
            MostCommon,
            CountAnswerBefore,
            CountAnswerAfter,
            CountVowel,
            CountConsonant,
            Unique,
            OnlySame,
        ],
    },
    DifficultyProfile {
        question_count: 10,
        allowed_types: &[
            CountAnswer,
            AnswerOf,
            AnswerIsSelf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            NextSame,
            PrevSame,
            LeastCommon,
            MostCommon,
            MostCommonCount,
            CountAnswerBefore,
            CountAnswerAfter,
            CountVowel,
            CountConsonant,
            Unique,
            OnlySame,
            LetterDist,
            EqualCount,
            ConsecIdent,
            OnlyOdd,
            OnlyEven,
            SameAsWhich,
        ],
    },
    DifficultyProfile {
        question_count: 12,
        allowed_types: &[
            CountAnswer,
            AnswerOf,
            AnswerIsSelf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            NextSame,
            PrevSame,
            LeastCommon,
            MostCommon,
            MostCommonCount,
            CountAnswerBefore,
            CountAnswerAfter,
            CountVowel,
            CountConsonant,
            Unique,
            OnlySame,
            LetterDist,
            EqualCount,
            ConsecIdent,
            OnlyOdd,
            OnlyEven,
            TrueStmt,
            SameAsWhich,
        ],
    },
];
