use crate::types::QuestionTypeKind;
use crate::types::QuestionTypeKind::*;

pub struct DifficultyProfile {
    pub question_count: usize,
    pub option_count: usize,
    pub allowed_types: &'static [QuestionTypeKind],
}

pub static PROFILES: [DifficultyProfile; 6] = [
    // Level 1: Intro
    DifficultyProfile {
        question_count: 3,
        option_count: 3,
        allowed_types: &[
            CountAnswer,
            CountAnswerBefore,
            CountAnswerAfter,
            AnswerOf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            SameAs,
            PrevSame,
            NextSame,
            MostCommon,
            LeastCommon,
            NoOtherHasAnswer,
        ],
    },
    // Level 2: Beginner
    DifficultyProfile {
        question_count: 4,
        option_count: 5,
        allowed_types: &[CountAnswer, AnswerOf, AnswerIsSelf, FirstWith, LastWith],
    },
    DifficultyProfile {
        question_count: 5,
        option_count: 5,
        allowed_types: &[
            CountAnswer,
            CountAnswerBefore,
            CountAnswerAfter,
            AnswerOf,
            AnswerIsSelf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            NextSame,
            PrevSame,
            SameAs,
        ],
    },
    DifficultyProfile {
        question_count: 8,
        option_count: 5,
        allowed_types: &[
            CountAnswer,
            AnswerOf,
            AnswerIsSelf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            NextSame,
            PrevSame,
            LeastCommon,
            MostCommon,
            CountAnswerBefore,
            CountAnswerAfter,
            CountVowel,
            CountConsonant,
            NoOtherHasAnswer,
            OnlySame,
            SameAs,
        ],
    },
    DifficultyProfile {
        question_count: 10,
        option_count: 5,
        allowed_types: &[
            CountAnswer,
            AnswerOf,
            AnswerIsSelf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            NextSame,
            PrevSame,
            LeastCommon,
            MostCommon,
            MostCommonCount,
            CountAnswerBefore,
            CountAnswerAfter,
            CountVowel,
            CountConsonant,
            NoOtherHasAnswer,
            OnlySame,
            SameAs,
            LetterDist,
            EqualCount,
            ConsecIdent,
            OnlyOdd,
            OnlyEven,
            SameAsWhich,
        ],
    },
    DifficultyProfile {
        question_count: 12,
        option_count: 5,
        allowed_types: &[
            CountAnswer,
            AnswerOf,
            AnswerIsSelf,
            ClosestAfter,
            ClosestBefore,
            FirstWith,
            LastWith,
            NextSame,
            PrevSame,
            LeastCommon,
            MostCommon,
            MostCommonCount,
            CountAnswerBefore,
            CountAnswerAfter,
            CountVowel,
            CountConsonant,
            NoOtherHasAnswer,
            OnlySame,
            SameAs,
            LetterDist,
            EqualCount,
            ConsecIdent,
            OnlyOdd,
            OnlyEven,
            TrueStmt,
            SameAsWhich,
        ],
    },
];
