import type { QuestionType } from "../engine/types.ts";

export interface DifficultyProfile {
  level: number;
  name: string;
  questionCount: number;
  optionCount: number;
  allowedTypes: QuestionType["type"][];
}

export const profiles: DifficultyProfile[] = [
  {
    level: 1,
    name: "Intro",
    questionCount: 3,
    optionCount: 3,
    allowedTypes: [
      "CountAnswer",
      "CountAnswerBefore",
      "CountAnswerAfter",
      "AnswerOf",
      "ClosestAfter",
      "ClosestBefore",
      "FirstWith",
      "LastWith",
      "SameAs",
      "PrevSame",
      "NextSame",
      "MostCommon",
      "LeastCommon",
      "NoOtherHasAnswer",
    ],
  },
  {
    level: 2,
    name: "Beginner",
    questionCount: 4,
    optionCount: 5,
    allowedTypes: ["CountAnswer", "AnswerOf", "AnswerIsSelf", "FirstWith", "LastWith"],
  },
  {
    level: 3,
    name: "Easy",
    questionCount: 5,
    optionCount: 5,
    allowedTypes: [
      "CountAnswer",
      "CountAnswerBefore",
      "CountAnswerAfter",
      "AnswerOf",
      "AnswerIsSelf",
      "ClosestAfter",
      "ClosestBefore",
      "FirstWith",
      "LastWith",
      "NextSame",
      "PrevSame",
      "SameAs",
    ],
  },
  {
    level: 4,
    name: "Medium",
    questionCount: 8,
    optionCount: 5,
    allowedTypes: [
      "CountAnswer",
      "AnswerOf",
      "AnswerIsSelf",
      "ClosestAfter",
      "ClosestBefore",
      "FirstWith",
      "LastWith",
      "NextSame",
      "PrevSame",
      "LeastCommon",
      "MostCommon",
      "CountAnswerBefore",
      "CountAnswerAfter",
      "CountVowel",
      "CountConsonant",
      "NoOtherHasAnswer",
      "OnlySame",
      "SameAs",
    ],
  },
  {
    level: 5,
    name: "Hard",
    questionCount: 10,
    optionCount: 5,
    allowedTypes: [
      "CountAnswer",
      "AnswerOf",
      "AnswerIsSelf",
      "ClosestAfter",
      "ClosestBefore",
      "FirstWith",
      "LastWith",
      "NextSame",
      "PrevSame",
      "LeastCommon",
      "MostCommon",
      "MostCommonCount",
      "CountAnswerBefore",
      "CountAnswerAfter",
      "CountVowel",
      "CountConsonant",
      "NoOtherHasAnswer",
      "OnlySame",
      "SameAs",
      "LetterDist",
      "EqualCount",
      "ConsecIdent",
      "OnlyOdd",
      "OnlyEven",
      "SameAsWhich",
    ],
  },
  {
    level: 6,
    name: "Expert",
    questionCount: 12,
    optionCount: 5,
    allowedTypes: [
      "CountAnswer",
      "AnswerOf",
      "AnswerIsSelf",
      "ClosestAfter",
      "ClosestBefore",
      "FirstWith",
      "LastWith",
      "NextSame",
      "PrevSame",
      "LeastCommon",
      "MostCommon",
      "MostCommonCount",
      "CountAnswerBefore",
      "CountAnswerAfter",
      "CountVowel",
      "CountConsonant",
      "NoOtherHasAnswer",
      "OnlySame",
      "SameAs",
      "LetterDist",
      "EqualCount",
      "ConsecIdent",
      "OnlyOdd",
      "OnlyEven",
      "TrueStmt",
      "SameAsWhich",
    ],
  },
];
