import type { ValidationRule } from "../engine/types.ts";

export interface DifficultyProfile {
  level: 1 | 2 | 3 | 4 | 5;
  name: string;
  questionCount: number;
  allowedTypes: ValidationRule["type"][];
}

export const profiles: DifficultyProfile[] = [
  {
    level: 1,
    name: "Beginner",
    questionCount: 4,
    allowedTypes: ["count_answer", "answer_of_question", "answer_is_self"],
  },
  {
    level: 2,
    name: "Easy",
    questionCount: 5,
    allowedTypes: [
      "count_answer",
      "answer_of_question",
      "answer_is_self",
      "closest_after",
      "first_with_answer",
      "last_with_answer",
      "same_answer_as",
      "next_same_answer",
    ],
  },
  {
    level: 3,
    name: "Medium",
    questionCount: 8,
    allowedTypes: [
      "count_answer",
      "answer_of_question",
      "answer_is_self",
      "closest_after",
      "closest_before",
      "first_with_answer",
      "last_with_answer",
      "same_answer_as",
      "next_same_answer",
      "previous_same_answer",
      "least_common_answer",
      "most_common_answer",
      "count_answer_before",
      "count_answer_after",
      "count_vowel_answers",
      "count_consonant_answers",
      "unique_answer",
      "only_same_answer",
    ],
  },
  {
    level: 4,
    name: "Hard",
    questionCount: 10,
    allowedTypes: [
      "count_answer",
      "answer_of_question",
      "answer_is_self",
      "closest_after",
      "closest_before",
      "first_with_answer",
      "last_with_answer",
      "same_answer_as",
      "next_same_answer",
      "previous_same_answer",
      "least_common_answer",
      "most_common_answer",
      "most_common_count",
      "count_answer_before",
      "count_answer_after",
      "count_vowel_answers",
      "count_consonant_answers",
      "unique_answer",
      "only_same_answer",
      "letter_distance",
      "equal_count_as",
      "consecutive_identical",
    ],
  },
  {
    level: 5,
    name: "Expert",
    questionCount: 12,
    allowedTypes: [
      "count_answer",
      "answer_of_question",
      "answer_is_self",
      "closest_after",
      "closest_before",
      "first_with_answer",
      "last_with_answer",
      "same_answer_as",
      "next_same_answer",
      "previous_same_answer",
      "least_common_answer",
      "most_common_answer",
      "most_common_count",
      "count_answer_before",
      "count_answer_after",
      "count_vowel_answers",
      "count_consonant_answers",
      "unique_answer",
      "only_same_answer",
      "letter_distance",
      "equal_count_as",
      "consecutive_identical",
      "only_odd_with_answer",
      "only_true_statement",
    ],
  },
];
